name: Deploy to development environment

on:
  push:
    branches:
      - "feature/*"
      - "fix/*"
  pull_request:
    branches:
      - "main"
      - "dev"

jobs:
  test:
    name: phpunit test
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password1
          MYSQL_DATABASE: todoList
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer:v2

      - name: Install dependencies
        run: composer install -n --prefer-dist

      - name: Copy .env
        run: cp .env.ci .env

      - name: Run migrations
        run: php vendor/bin/phinx migrate
        env:
          DB_HOST: 127.0.0.1

      - name: Run tests
        run: vendor/bin/phpunit
        env:
          DB_HOST: 127.0.0.1
