name: Deploy to development environment

on:
  push:
    branches:
      - "feature/*"
      - "fix/*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    name: phpunit test
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password1
          MYSQL_DATABASE: todoList
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t todo-list-app ./todoList

      - name: Run Docker container
        run: docker run -d --name todo-list-app-container --network host todo-list-app

      - name: Run migrate
        run: docker exec todo-list-app-container php vendor/bin/phinx migrate

      - name: Run tests
        run: docker exec todo-list-app-container vendor/bin/phpunit
        env:
          DB_HOST: 127.0.0.1
