name: Deploy to development environment

on:
  push:
    branches:
      - "feature/*"
      - "fix/*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    name: phpunit test
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password1
          MYSQL_DATABASE: todoList
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h 127.0.0.1 --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer:v2
      - name: go to todoList
        run: cd todoList

      - name: check todoList
        run: ls -a

    #   - name: Run migrate
    #     run: docker exec todo-list-app-container php vendor/bin/phinx migrate
    #     env:
    #       DB_HOST: 127.0.0.1

    #   - name: Run tests
    #     run: docker exec todo-list-app-container vendor/bin/phpunit
    #     env:
    #       DB_HOST: 127.0.0.1
